route:
  receiver: ntfy-bridge
  group_by: ['container_name']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: ntfy-bridge
    webhook_configs:
      - url: http://ntfy-bridge:8183/
        send_resolved: true
